services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: MySecretKey123!